### ISSUE TITLE
Wav/WavStream audio crackling

### ISSUE THREAD

**Issue by leiradel** [jarikomppa/soloud#183]
> Expected behavior:

Perfect audio.

> Actual behavior:

Audio crackling, right channel only.

> Steps to reproduce the problem:

Load a WAV or OGG using either `Wav` or `WavStream`, start playing and mixing. It's easier to hear the crackling with a low volume for the voice.

> SoLoud version, operating system, backend used, any other potentially useful information:

```c++
#define SOLOUD_VERSION 201800
```

I'm using the null backend to mix the sound to use in a [libretro](https://www.libretro.com/) core. I've just integrated SoLoud, before I was using my own audio mixer with WAV and OGG support only and the mixing was ok. I was using stb_vorbis too, but it doesn't seem to be related to it wince WAV files also present the issue.

[//]: # ( You don't need to follow the above template if you do not want to; feel free to start from scratch. )
[//]: # ( Following the template leads to problem reports that are helpful to the developers. )
[//]: # ( ...yes, this weird syntax is how one writes comments in a markdown file )

**Comment by leiradel** [comment]
Hi, I'm also playing `Sfxr` and `Speech` sounds and they sound ok. It's odd that the crackling seems to be in the right channel only.

Everything in my setup is pretty standard, I'm clueless about what could be causing the issue.

**Comment by leiradel** [comment]
[sketch008.zip](https://github.com/jarikomppa/soloud/files/2108224/sketch008.zip)

This file has one of the OGG files that I tested, and a WAV file with the output of `mixSigned16`.

**Comment by jarikomppa** [comment]
This was probably fixed by: https://github.com/jarikomppa/soloud/commit/b54020bfcbed24df19406a06fdbc32403150cc2d because you said the crackling was in right channel only and that mono sources worked. Please reopen if this wasn't the case.

**Comment by leiradel** [comment]
Thanks for responding. I've pulled the latest code from the repository and the issue persists.

**Comment by jarikomppa** [comment]
Ah, I thought the problem was that there's weird crackling on the right channel, but now that I check your waves.. there's only sound on the right, and it's crackling.

- The issue can't be about the file loading, because then it just wouldn't work.
- I doubt this is a platform-specific issue, but you never know.
- You're using the null backend, so it's (probably) not the back end.
- Symptoms: Mono sources work. Stereo sources act up.

I'd love to be able to reproduce the bug..

Can you compile and run sanity? (src/tools/sanity, link against soloud sources). Sanity doesn have a test to check if left or right channels are quiet, though, so it probably doesn't hit this specific issue, but at least if something pops up, we know it's a portability issue.

**Comment by jarikomppa** [comment]
Further elimination: since mono sources work, it's not about the 16 bit mix function.
I've also played the ogg through various backends with no problems, so it's not the ogg decoding. The ogg file itself is also fine. Playing the ogg through the null driver looks fine too.

**Comment by jarikomppa** [comment]
This produced a raw file that I could import into audacity and play fine:
```
#include <stdlib.h>
#include <stdio.h>
#include "soloud.h"
#include "soloud_wav.h"

int main(int argc, char *argv[])
{
	SoLoud::Soloud soloud;
	SoLoud::Wav wav;
	wav.load("audio/sketch008.ogg");
	soloud.init(SoLoud::Soloud::CLIP_ROUNDOFF, SoLoud::Soloud::NULLDRIVER);
	soloud.play(wav);

	FILE * f = fopen("audiodump.raw", "wb");

	while (soloud.getActiveVoiceCount() > 0)
	{
		short ibuf[256 * 2];
		soloud.mixSigned16(ibuf, 256);
		fwrite(ibuf, sizeof(short), 256 * 2, f);
	}
	fclose(f);

	soloud.deinit();
	return 0;
}

```

**Comment by leiradel** [comment]
> Can you compile and run sanity?

```
$ ./sanity 
lastknown.wav not found, writing one.
SoLoud version 201800
Backend 13: null driver, 2 channels, 44100 samplerate, 2048 buffersize

168 tests, 0 error(s) 
lastknown.wav written.

$ ./sanity 
SoLoud version 201800
Backend 13: null driver, 2 channels, 44100 samplerate, 2048 buffersize

241 tests, 0 error(s) 
```

I also tested the raw file converted to a wave by Audacity. In audacity the audio is correct, but the crackling persists in my application. I must be doing something wrong on my side, probably something in my audio backend. I use PhysicsFS, but I'm pretty sure I'd had a much bigger problem if it was messing up with the OGG reading.

Sorry for the false positive.

**Comment by jarikomppa** [comment]
I still don't get it though; you said mono sources worked, and you recorded
off the mix function..

Fwiw, right channel seems to be the first one.

If you can figure out what was wrong, I'd love to hear about it; if you
find that the problem is on soloud's side, a minimal test source would be
nice.

**Comment by leiradel** [comment]
Ok, I've tried somethings and the cracks were always there:

* I've dumped the raw buffer contents right after the call to the mixing function
  * Tried Stereo S16, stereo F32, mono S16
  * No tampering with the samples
* I've zeroed the buffer before calling the mixing function
  * Just in case
* I've used double buffering in my mixing function
  * Maybe the code that was sending the samples to the hardware was messing with the contents of the buffer
  * Unlikely because it copies the samples to a different buffer
* I've used standard SoLoud IO by directly passing the path to the OGG file on disk
  * No PhysicsFS involved
* I've converted the OGG to WAV and used it in the application
  * No OGG decoding involved
* I've removed all other sounds and let only the OGG playing
  * No mixing of multiple voices

The only time it worked was when I set the OGG volume to 1.0f, but then I don't know if it really worked or if the cracks were just inaudible. I've converted the OGG to raw using a minimal application using a volume of 0.2f and it worked.

All source code was always compiled with the same compiler flags.

I'm puzzled. If you have any other test that I can make please let me know.

**Comment by jarikomppa** [comment]
You say it worked when you set the ogg volume to 1.0f. What are you
normally setting it to?

**Comment by jarikomppa** [comment]
Try enabling floating point debug to see if NaNs creep in somehow: define
FLOATING_POINT_DEBUG

**Comment by leiradel** [comment]
I had to change the code to use `feenableexcept` since I'm using Linux, but then I got a FP exception on an unrelated code :(

My application is a libretro core and I'm using RetroArch to run it, I can't easily fix the exception, nor compile my application to run without RetroArch.

**Comment by jarikomppa** [comment]
This starts to be a complete shot in the dark, but maybe libretro is
setting the fpu into some mode that causes soloud to generate NaNs in some
cases..

Does your compiler have options for floating point accuracy? As in fast vs
precise stuff. Those might be worth a try.

**Comment by lamelizard** [comment]
Peace, I'm facing a mostly same problem:

using Null driver
in a libretro core
using mix() (not the 16bit version)
the right channel crackles (I manually switched the channels in between soloud and retroarch -> it's the right soloud channel that crackles)

So I compiled with FLOATING_POINT_DEBUG on Windows x64 and ran it again, but nothing new happened.
But I don't know what should have happened, does nothing mean that there are no NANs?

**Comment by leiradel** [comment]
> This starts to be a complete shot in the dark

Yeah, I'm out of ideas too.

> maybe libretro is setting the fpu into some mode

Unlikely. I've had trouble in the past with DirectX changing the FP rounding mode, but I'm on linux with OpenGL.

> Does your compiler have options for floating point accuracy?

It does, but I don't really think it could be the reason of the cracks.

@lamelizard if you dump raw samples right after `mix` and open the file in Audacity, are the cracks there?

**Comment by jarikomppa** [comment]
This is one ping-pong open-close issue but I want to see how deep this rabbit hole goes..

**Comment by lamelizard** [comment]
Sadly my project has a plugin manager and several abstration layers between soloud and libretro plus a custom cmake file for soloud...
So my guess is that @leiradel 's core might be far easier to test with. @leiradel, your retroluxury core was it what you opened this issue for?

**Comment by jarikomppa** [comment]
Got it compiled and running under visual studio. There's definitely some noise on the right channel, but the left channel isn't quiet.. anyway, this is something I can look at.

**Comment by jarikomppa** [comment]
Righty-o.
The requested number of samples is not divisible by 4, but the clip function expects that as it uses SIMD to handle four samples at a time.  735 samples / 4 = 183 * 4 = 732, so a few samples get missed.
Fix is to round things up, and process a few samples too many (these are scratch buffers so there's room for a couple extra samples). Fix is in 487c0140509576235d3d5b7c589b552e4ee160f4

**Comment by jarikomppa** [comment]
I'm waiting for confirmation before closing this, even though that was a pretty clear bug.

**Comment by leiradel** [comment]
Ah yes, the core runs at 60 FPS and sets the audio output to 44100 Hz, so it wants 735 stereo samples per video frame.

Thanks so much for looking into this, I'll test the fix later and will let you know.

**Comment by jarikomppa** [comment]
fwiw for visual studio build, I dumped all the source files to a visual studio project, set up paths, removed all restrict keywords, added dllexport declspecs to all of the libretro functions, and the thing compiled. Didn't get the zip files to work but using a direct directory did.

**Comment by leiradel** [comment]
I confirm the fix works for me, thanks again.
