### ISSUE TITLE
Assert from deinit() on shutdown

### ISSUE THREAD

**Issue by greg-churchillnavigation** [jarikomppa/soloud#241]
This assert fired once on shutdown.

```
	void Soloud::deinit()
		SOLOUD_ASSERT(!mInsideAudioThreadMutex);
```

No repro. Only occurred once ever in many app runs.

Is there any other possible shutdown steps or recommended shutdown/delete order of AudioSources, Buses, System?

**Comment by greg-churchillnavigation** [comment]
This happened a 2nd time today (after weeks).

I see Soloud::~Soloud() uses sequence with comment

```
		// let's stop all sounds before deinit, so we don't mess up our mutexes
		stopAll();
		deinit();
```
I'll ensure stopAll() is called first.

**Comment by jarikomppa** [comment]
Everything should(tm) clean up fine, but with threads in play anything can happen. What platform and what backend are you using?

**Comment by greg-churchillnavigation** [comment]
Building under Windows with default backend.
Explicitly calling stopAll() before deinit() resolves this issue, so can be closed unless you want to update code to call stopAll() within deinit() same as destructor.
Thanks!

**Comment by jarikomppa** [comment]
Done. Good catch!

**Comment by rversteegen** [comment]
Hello,

Please reopen; this bug is back and it happens 100% of the time when running the `enumerate` demo from latest git head, on linux x86_64. The other demos compiled by the generated makefile have no problem

```
> ./enumerate 
-----
Backend 0:AUTO
ID:       7
String:   "ALSA"
Rate:     44100
Buffer:   4096
Channels: 2 (stereo) (default)
enumerate: ../../src/core/soloud.cpp:192: void SoLoud::Soloud::deinit(): Assertion `!mInsideAudioThreadMutex' failed.
fish: “./enumerate” terminated by signal SIGABRT (Abort)
```

**Comment by jarikomppa** [comment]
I think I've figured out what's going wrong in this case, and have a solution.
